In [1]:
import numpy as np

In [12]:
a = np.array([2, 4, 5])
print("array:", a)

b = [2, 4, 5]
print("list:", b)
print(type(a),"\n",type(b))

array: [2 4 5]
list: [2, 4, 5]
<class 'numpy.ndarray'> 
 <class 'list'>


In [14]:
y = np.linspace(0, 20, 7)
print(y)

[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.        ]


In [21]:
m = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print(m)
print(type(m))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [27]:
n = np.arange(0, 100, 20)
print(n)

[ 0 20 40 60 80]


In [28]:
z = np.zeros((2, 2))
print(z)

[[0. 0.]
 [0. 0.]]


In [31]:
o = np.ones(16)
print(o)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [33]:
o_reshaped = o.reshape(4, 4)
print(o_reshaped)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
o_reshaped_1 = o.reshape(2, 2, 4)
print(o_reshaped_1)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [35]:
r = o.ravel()
print(r)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [38]:
q = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
print(np.vstack(q))
print(np.hstack(q))

[[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]
[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [39]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
print(m.shape)
print(m.ndim)
print(m.itemsize)

(3, 3)
2
4
